### ISSUE TITLE
while calling 'scrollTo' api it throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-treeview#2]
**ERROR
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'width: 352px'. Current value: 'width: auto'.**

Step: click the 'Scroll to ...' button on the demo page

https://stackblitz.com/edit/integralui-treeview-overview-sbmsyl

![image](https://user-images.githubusercontent.com/1568013/103842377-c4cb2780-50d0-11eb-9204-ff7bc51d03df.png)

**Comment by Lidor-Systems** [comment]
Change the code line with ViewChild for TreeView in beginning from false to true.

```
@ViewChild("treeview", { static: true }) treeview: IntegralUITreeView;
```

You can find more information about [static field in Angular official documentation](https://angular.io/guide/static-query-migration).

**Comment by MM-RYO** [comment]
> Change the code line with ViewChild for TreeView in beginning from false to true.
> 
> ```
> @ViewChild("treeview", { static: true }) treeview: IntegralUITreeView;
> ```
> 
> You can find more information about [static field in Angular official documentation](https://angular.io/guide/static-query-migration).

It's already set to true. but the issue is still there. 

angular version: 9.1.12
integralui: 20.2.0

**Comment by Lidor-Systems** [comment]
Thank you for your information.

We have found what is causing this error. Apparently, the width of the item hovering content changes twice during TreeView layout update. We have changed the code that handles this, so now this error is no longer thrown. We have tested the solution under Angular version 10 and its working.

Sometimes this kind of errors are very difficult to detect. Because Angular changes the way components are updated, the code that was working previously without errors, with new Angular updates may cause a problem. This is rare thing, but it can happen.

An updated version is already sent to your company representative. Please let us know, whether its working on your side.

**Comment by Lidor-Systems** [comment]
We would recommend you in future projects to try out our IntegralUI TreeView - Web Component, which you can find under integralui web - treeview/web components/bin/Integralui/components folder. 

It is a native web component, independent from other frameworks and you can use it in Angular, React, Vue or any other JavaScript framework. Any changes to Angular will not affect this component, and the benefits are: smaller size, faster and more maintainable.

A free version of this component is also available as standalone or as part of [IntegralUI Web Lite](https://github.com/lidorsystems/integralui-web-lite).
